language: python
python:
  - "2.7"
  - "pypy"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq memcached
  - sudo service memcached start
install:
  pip install . --use-mirrors
script: python setup.py test
